mindmap
  root((deeplearning))
    Neural Networks
      MLP["Multi-Layer perceptron (MLP) or (FCN)"]
        Components
            Fully Connected
            Activation Function
        Usage
            Regression
            Classification 
      CNN["Convolutional Neural Networks (CNN)"]
        Components
            Conv
                Kernel["Kernel or filter"]
                Stride
                Padding
            Downsampling
                MaxPool
                AvgPool
        Usage
            image
    Optimizers
        Adam
    Loss functions
        CrossEntropyLoss
    Regularization
        Dropout
    Techniques
        Weight Initialization
            Kaiming Normal
            Xavier Normal
